[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "iclots"
authors = [{name = "Meredith Fay, PhD", email = "meredith.fay@iclots.org"}]
dynamic = ["version", "description"]
